### ISSUE TITLE
Update Shopware 6.6.6.0 OverwritePaymentMethodRoute.php on line 41 and exactly 3 expected

### ISSUE THREAD

**Issue by rmoecklideveloper** [mediaopt/moptworldline#22]
3.1 shall be compatible, so I updated the plugin, ok
then updated shopware from 6.6.5.1 to 6.6.6.0 and now Error:
Too few arguments to function Shopware\Core\Checkout\Payment\SalesChannel\PaymentMethodRoute::__construct(), 1 passed in /var/www/sdbb/shopware/custom/plugins/MoptWorldline/src/Core/Checkout/Payment/SalesChannel/OverwritePaymentMethodRoute.php on line 41 and exactly 3 expected

I deactivated the plugin by DB active =0 so far

can you make it work for this shopware version please

![Bildschirmfoto 2024-09-13 um 11 01 50](https://github.com/user-attachments/assets/aab6ff51-16e8-402b-8ece-7c10a5f9f41e)

**Comment by rmoecklideveloper** [comment]
nobody else with this issue after update?

**Comment by adorebikes** [comment]
We have the exact same issue with Shopware 6.6.6.0

**Comment by hmustafa-d2** [comment]
same here

**Comment by adorebikes** [comment]
Mediaopt is apparently working on a solution :)

**Comment by LiudmylaMasliuk** [comment]
Hello, yes, we are aware of the issue and we are working to fix it as fast as possible. Thank you for your patience.

**Comment by hbmdpt** [comment]
Hello, this has been fixed in the plugin version 3.1.1. Thank you all for your patience. Please contact support@mediaopt.de if you have any other inquiries.
